### ISSUE TITLE
Good First Issue For Contributors

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#1461]
Hi, if you are reading this is because you pretty likely don't know how to start 🤔 . Fair enough !

> ⚠️ Use the branch `5.x` and don't forget to [read the contribution guidelines])https://github.com/verdaccio/verdaccio/blob/5.x/CONTRIBUTING.md).

So, let's work on that 🚸 !

## What should I know before start?

All here we are developers with different backgrounds, languages and objectives. But, all we must follow certain rules so we can understand each other and make the communication easier as possible. Please 👍  read your [code of conduct](https://github.com/verdaccio/verdaccio/blob/master/CODE_OF_CONDUCT.md), long story short, just **be nice with everybody around here**.

- **Code guidelines**: we enforce them using `eslint`, so you don't have to read a long list of rules, we love automation 🤖 .
- **Commit guidelines**: We follow the [semantic versioning approach](https://github.com/verdaccio/verdaccio/blob/5.x/CONTRIBUTING.md), this is really important so your PR will appear on the Changelog 🎉 ! I guess you expect recognition and we will give it to you.

That's all you need to know before start.

## What can I do?

I'd assume you are completely lost 😩, that's fine! I was it when I get started on this. Let me help you. 

You are in **verdaccio** core project, but actually, we have 3 repositories you can contribute. 

* **verdaccio/ui**: https://github.com/verdaccio/ui (React Hooks + Webpack + Typescript + CSS3) [Click here for more tickets](https://github.com/verdaccio/ui/labels/hacktoberfest%20%F0%9F%8E%83)
* **verdaccio/docker-examples**: https://github.com/verdaccio/docker-examples (Docker)
* **verdaccio/website**: https://github.com/verdaccio/website (Docusaurus + React)

If you are interested in **Typescript** in general, here some ideas you might help

* [ ] Get rid of `@ts-ignore`. 
* [ ] Remove `any` and add proper types. 
* [ ] Fix `eslint` warnings for `@typescript-eslint/xxx`. 
* [ ] Improve our `@types` https://github.com/verdaccio/verdaccio/tree/5.x/packages/core/types (better naming, document each type, remove duplications)

If you are interested mostly on Front-End, we use **React@16.x** 

* [x] Migrate components to React Hooks https://github.com/verdaccio/ui/issues/116
* [ ] Increase component coverage (either `enzyme` or `react-testing-library`
* [x] Add **i18n** to the UI https://github.com/verdaccio/ui/issues/102
* [ ] [Fix bugs](https://github.com/verdaccio/ui/issues?q=is%3Aissue+is%3Aopen+label%3Abug) They are really [simple ones](https://github.com/verdaccio/ui/labels/good%20first%20issue) 🔰  

If you like **Docker**:

- [ ] Add new examples, integrations with Apache, Nginx or whatever is missing and helps other to doit themselves. https://github.com/verdaccio/docker-examples
- [ ] Improve Helm Charts https://github.com/verdaccio/charts

If you like **Website**:

- [ ] New website design (https://github.com/verdaccio/website/issues/75) Contribute here -> #1843 
- ~Update to Docusaurus V2~ Discarted
- [ ] Translate to [new languages](https://github.com/verdaccio/website#how-to-help-with-translations)

If you like **GitHub Actions**:

- [ ] Put on shape our actions https://github.com/verdaccio/github-actions

In general, you might help with other things as:

- [ ] Rename variable names 👍 if you considere is not well readable
- [ ] Fix `FIXME://` comments 
- [ ] Add new plugins for the community [here](https://github.com/verdaccio/monorepo/tree/master/plugins) ⚠️ we will add some guidelines how to do it.
- [ ] Fix `// eslint-disable-next-line new-cap` **eslint** inline comments
- [ ] Add/Fix/Improve test to Verdaccio, [here a complete guideline](https://github.com/verdaccio/verdaccio/blob/master/test/README.md).

If you have any suggestions, just feel free to comment this thread, or chat me over Discord 🙃 , if you are shy I accept DM over Discord. Let's us help you to grow in Open Source.

🗣 http://chat.verdaccio.org

🎉 We are ready for https://hacktoberfest.digitalocean.com/ **Hacktoberfest 2020

## Before PR

* Keep the PR small as possible and one single topic for each
* If you don't change the logic, then ignore modify the test if you don't need it

**Comment by juanpicado** [comment]
Thanks guys ! I will share soon the stats of contributions 🥳🥰
