### ISSUE TITLE
feat: deprecation

### ISSUE THREAD

**Issue by frank-dspeed** [verdaccio/verdaccio#1635]
## Goals
accept 
```bash
npm deprecate <pkg>[@<versionOrRange>] <message>
yarn deprecate <pkg>[@<versionOrRange>] <message>
```
as i need to reverse engineer that for yarn anyway i can integrate it here fast also.

## TODO
offer the same api as npm does and add "deprecated": "msg" filds to the manifest on download
- https://github.com/verdaccio/verdaccio/blob/master/src/api/endpoint/api/publish.ts#L98
  -  [x] Will need to check if the puted data is a deprecate reqest some how need examin headers.
  -  [x] its a Put request to the HTML escaped version of spec.name   npmjs.org/spec.escapedName
  -  [x] needs semver checks for the supplyed version range exprensiv operation
  -  [x] need to check how the version range get suppyled by npm 
  -  [ ] integrate https://github.com/npm/npm-pick-manifest

## Related Yarn issue
- https://github.com/yarnpkg/yarn/issues/4943

## Current Development Branch
- https://github.com/direktspeed/verdaccio/tree/feat-deprecate

## Current Ui Implamentation
- https://github.com/verdaccio/ui/issues/67

## Blocking needs Discussion Questions that are importent 
Feature Design Considerations some stuff needs to get splitted up in own issues as they are global questions. will prepare more detailed Issues.

#### The Main Problem that comes up is! 
Befor this implamentation we could assume that data will not change npmjs.org will be consistent package meta don't changes.

After this implamentation we deal with the fact that the deprecation status can change after we have fetched a copy of the package.
- [ ] We need to implament some form of last checked State from the upstream
  - some kind of extra fild lastChecked its not allowed to get added to the package.info
- [ ] We need to handle user Permissions will it be possible to deprecate packages that you don't manage for example in a use case where a user installs this as proxy and don't registers users he will fetch packages that he could deprecate some how?
- [ ] Should this inhire pull the NPM Or Upstream Registry deprecation meta infos
- [ ] Schould this also run deprecate against the upstream Registrys?
- [ ] When a NPM Package is not deprecated but we have a deprecated version?
- [ ] When a NPM Package is deprecated but we have a none deprecated version?
- [ ] deprecation state needs sync with upstream registrys
- [ ] plugin authority-registry
  - Current Standard behavior ask upstream only if we don't got infos
  - but stores indipenden deprecation messages.if present deprecation behavior needs to be set explizit if it should inhire from source registry or not
- [ ] plugin proxy-registry
  - if we know we run as a offline proxy 
  - if we know we are a additional cache for npm

**Comment by DanielRuf** [comment]
>     * extract tar edit package json repackage.

This would change the integrity hash which breaks it. We should not do that.

**Comment by DanielRuf** [comment]
See https://github.com/verdaccio/verdaccio/pull/1308

We may just need the TypeScript version @honzahommer

**Comment by frank-dspeed** [comment]
@DanielRuf at present its not needed your right the right way is to serve a updated packet manifest…

**Comment by DanielRuf** [comment]
I don't agree and I don't fully understand your answer.

Did you check the linked PR and how npm does it normally?

Checksums should never change. Only the metadata on the registry might be updated (`deprecated` field).

**Comment by juanpicado** [comment]
> extract tar edit package json repackage.

We don't unpack tarballs, same though as @DanielRuf . I have an idea why `yarn` haven't implemented `npm deprecated` but,  Is there any official statement about this?

I wanna implement `npm deprecate` before, but turned out don't be that easy https://github.com/verdaccio/verdaccio/pull/1308#issuecomment-498117579 . Any solution should fit in our current design and backward compatible. 

As far I know `npmjs` only add `"deprecated": "Unknown status of this version",` a prop within the metadata, but this get in conflict with `npm start` or something like that.

**Comment by frank-dspeed** [comment]
@juanpicado its not implamented in yarn because of the proxy for yarn packages that existed that don't supported that call like verdaccio don't supports that call but that is deprecated all now now deprecate can be supported as yarn is moved do npmjs.org

**Comment by DanielRuf** [comment]
Yarn is not a proxy since a few years anymore. It's the same CDN / registry afaik.

**Comment by DanielRuf** [comment]
Related: https://github.com/verdaccio/ui/issues/67

**Comment by julmot** [comment]
Related: #1280

**Comment by juanpicado** [comment]
Closing in favor the relates one.

Thanks :)
