### ISSUE TITLE
Verdaccio 5 Roadmap

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#1690]
Hi, I'm @juanpicado and the intent of this story (epic) is to describe what we would like to have for Verdaccio 5.

> ⚠️ Any  of the following features must start from the branch `5.x`

https://github.com/verdaccio/verdaccio/commits/5.x

Docker https://github.com/verdaccio/verdaccio/packages/13531

```bash
docker pull docker.pkg.github.com/verdaccio/verdaccio/verdaccio:5.x
```

:information_source:  npm package not available yet, only usable running `pnpm start` from root

This year we will have a longer release, the project has grown and with a long tail of users and at this point, we did not want to introduce big breaking changes in order to keep the backward compatibility. 
Verdaccio 5 will keep the nature of the predecessors, simple, zero-configuration need it, lightweight and open-source but with **a few breaking changes**.

The project needs to evolve and might break some plugins or configurations, so in order to achieve a calm transition *beta* and *alpha* will be longer, as usual, better migration guides and so on, not to mention we are doing this on **our spare time**.  We will define a final date release when we are sure we have enough topics closed. Verdaccio 4 still will be the major release and maintained as usual.  

As a reminder, [we accept donations](https://opencollective.com/verdaccio), this helps keep motivation up and move things faster.

> I will provide canary npm versions eventually, in the meaning feel free to use the docker version `5.x-next`.

If you want to contribute, feel free to open a discussion about any of these topics, or something else you think would be relevant, do not hesitate to reach me out.

### Structure

Verdaccio has several repositories and will contribute to the next major release. 

* [Verdaccio UI (React)](https://github.com/verdaccio/ui): The default web embebed with Verdaccio made in React and Typescript.
* [GitHub - verdaccio/docker-examples: 🐳 ⛴A collection of Docker and Kubernetes examples for verdaccio](https://github.com/verdaccio/docker-examples)
* [Verdaccio Core](https://github.com/verdaccio/verdaccio): The main project, the CLI registry.

This ticket is only about **Verdaccio Core**, the other projects have a **a continuous delivery release**, contributions follow semver and are shipped whenever are ready. This makes much easier our job and we can share responsibilities with multiple contributors and maintainers. Each project has it owns board where you can follow progress.

If you want to track the progress you can either:

* [5.x.x Milestone · GitHub](https://github.com/verdaccio/verdaccio/milestone/22)
* [Development · GitHub](https://github.com/verdaccio/verdaccio/projects/14) : This projected track all development of any version.

### Stack

This is the first step, we must modernize first the stack before goes with any other ticket to avoid complex refactorings (this is currently in progress)

* [x] [feat: migrate yarn workspaces by juanpicado · Pull Request #1546 · verdaccio/verdaccio · GitHub](https://github.com/verdaccio/verdaccio/pull/1546)
* [x] ~Apply latest `@verdaccio/babel-preset` and `@verdaccio/eslint-config`, `@verdaccio/types`.~ 
* [ ] Reduce usage of `callbacks` and promote `Promises`.
* [ ] [clean up eslint warnings · Issue #46 · verdaccio/monorepo · GitHub](https://github.com/verdaccio/monorepo/issues/46)
* [x] ~[feat: use readable-stream 3 · Issue #32 · verdaccio/monorepo · GitHub](https://github.com/verdaccio/monorepo/issues/32)~
* [ ] Replace request by "xxxx" https://github.com/verdaccio/verdaccio/issues/1807

#### Plugins

The Plugin support, the main pain comes from there, here a resume of the tickets we would like to address in the major release.

* [ ] [Multiple Authentication Plugins · Issue #1442 · verdaccio/verdaccio · GitHub](https://github.com/verdaccio/verdaccio/issues/1442)
* [ ] [Forcibly republish the package with the same version · Issue #1402 · verdaccio/verdaccio · GitHub](https://github.com/verdaccio/verdaccio/issues/1402)
* [ ] [Plugin System is weird · Issue #1394 · verdaccio/verdaccio · GitHub](https://github.com/verdaccio/verdaccio/issues/1394)
* [ ] [Collisions between main verdaccio and plugins configuration · Issue #928 · verdaccio/verdaccio · GitHub](https://github.com/verdaccio/verdaccio/issues/928)
* [ ] [Harmonize configuration options · Issue #925 · verdaccio/verdaccio · GitHub](https://github.com/verdaccio/verdaccio/issues/925)
* [ ] [Support for multiple access groups in plugins API (access, publish) · Issue #916 · verdaccio/verdaccio · GitHub](https://github.com/verdaccio/verdaccio/issues/916)
* [ ] [Allow scopes for loading plugins](https://github.com/verdaccio/verdaccio/issues/1867) #1867 
* [ ] Allow middleware to add layers on different parts of the request (being, end, etc ...) https://github.com/verdaccio/verdaccio/issues/1815#issuecomment-729044946

#### Endpoints

* [x] [Add support for new search endpoint · Issue #310 · verdaccio/verdaccio · GitHub](https://github.com/verdaccio/verdaccio/issues/310) PR https://github.com/verdaccio/verdaccio/pull/1732
* [ ] [Feature request: deprecate packages · Issue #1280 · verdaccio/verdaccio · GitHub](https://github.com/verdaccio/verdaccio/issues/1280)

#### Fix Legacy

* [ ] [Deprecation Warning: crypto.createDecipher is deprecated. · Issue #1689 · verdaccio/verdaccio · GitHub](https://github.com/verdaccio/verdaccio/issues/1689)
* [ ] [Get rid of async dependency · Issue #1225 · verdaccio/verdaccio · GitHub](https://github.com/verdaccio/verdaccio/issues/1225)
* [x] [Replace bunyan by Pinojs · Issue #1334 · verdaccio/verdaccio · GitHub](https://github.com/verdaccio/verdaccio/issues/1334)
* [ ] Using plugging for custom format logger
* [ ] [Allow other password encryptions · Issue #33 · verdaccio/monorepo · GitHub](https://github.com/verdaccio/monorepo/issues/33)
* [ ] [Syntax highlighting in README.md · Issue #245 · verdaccio/monorepo · GitHub](https://github.com/verdaccio/monorepo/issues/245)
* [ ] [refactor: use mkdirSync with the recursive option instead of mkdirp by DanielRuf · Pull Request #1335 · verdaccio/verdaccio · GitHub](https://github.com/verdaccio/verdaccio/pull/1335)
* [ ]  Fix ` DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.` message
* [x] feat: remove support for allow_ prefix #1741 
 
#### UI

* [ ] [Link to homepage filtered by keyword · Issue #1226 · verdaccio/verdaccio · GitHub](https://github.com/verdaccio/verdaccio/issues/1226)
* [ ] [Configurable UI features · 
  *  Issue #1539 Configurable Login Button
  *  Issue #1720 Hide pnpm instructions on web interface
* [x] ~~[Use custom favicon · Issue #1593 · verdaccio/verdaccio · GitHub](https://github.com/verdaccio/verdaccio/issues/1593)~~ Moved to 4.x

#### Project

* [ ] Add Governance file
* [x] Update contributions guidelines
* [ ] Close all `documentation` open at website [Issues · verdaccio/website · GitHub](https://github.com/verdaccio/website/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation)
* [ ] [New Website Design · Issue #75 · verdaccio/website · GitHub](https://github.com/verdaccio/website/issues/75)
  * [ ] Decide whether continous using *Docusaurus* or move to *GatbyJS*
* [ ] Build and publish from Docker at GitHub registry 
  * [x] Docker 5.x publish on push (master) #1744 
* [x] Unify repositories under **pnpm** monorepo #1884
  - [ ] website (partially done, once the website is ready, the website repo should be deprecated and archived) #1862 
  - [x] plugins and core packages from monorepo #1981 #1978 #1977 #1977 #1976 #1975 
- [x] Setup changesets #1913 

This is a quite long list of tickets, most of them won't be achieve without your help. Verdaccio maintainers has as firs task guard for stability, help community, bug fixes, releases, promotion and as last in this list improvements. 

> We don't expect any change in the Docker 🐳 image unless any plugin task force to it.

Feel free to comment any of the tickets if you have further questions.

**Comment by crper** [comment]
awesoem !

**Comment by crper** [comment]
awesome!

**Comment by dnafication** [comment]
Do we also need to look into fixing the CodeQL errors? Its seems to be complaining about valid issues like hardcoded header values etc.

**Comment by juanpicado** [comment]
No, that's something we are using in a experimental way. Ignore them for now please.
