### ISSUE TITLE
feat: website with GatsbyJS

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#1862]
This is the first try using GatsbyJS as website:

## Goals

- To have a more flexible website
- Be able to add new pages based on different sources (GitHub, Markdown, etc etc)
- Improve SEO experience
- Custom versioning (nice to have): We don't want to build versioning for each change, versioning should be immutable. Eg: If we are on `v5.0.0` and we release a patch version, the `v5.0.0` will pass a subfolder in the CDN and we do no to have to build it again, the `master` would be the one is under the root domain. This reduce the amount of MB we need to upload to the CDN every time we do a release. 
- Translations, with Crowdin we can fetch all translations on CI and build the website, we don't want to merge big PR every time someone change something on the crowdin platform.
- Custom design  https://github.com/verdaccio/website/issues/75#issuecomment-544070908

❤️ help is very welcome, otherwise it will take a while 😊 

This is only for `5.x` branch

In reference to https://github.com/verdaccio/website/issues/248

## Development

```
pnpm install
cd website
pnpm develop
```

Gatsby.js documentation applies to this website.

## Tasks

Each task might be a new PR on top of this branch `feat-website`

- [ ] Integrate with crowdin (currently I copied some translations to make it work): Translations should be downloaded in compile time, unpackage them and generate all pages.
- [ ] Restore auto deployment to the CDN (already works here https://github.com/verdaccio/website_2.0)
- [ ] Mobile ready (should be easy to navigate on mobile)
- [ ] Create layout (layout for mobile and desktop
- [ ] Improve navigation (navigation, switch languages, forward and backwards according the sidebar navigation)
- [ ] Create design (there is one proposal already)
- [x] Create doc pages
- [x] Create scaffolding with GatsbyJS  #1843

> ⚠️  If you want to just PR something small, any typo, linting, new TS type or micro change is very welcome.

**Comment by semoal** [comment]
Hey folks  👋🏻, I don't want to join on something where no one has called me, but what about of using Docusaurus v2? Natively accepts i18n with platforms like Crowdin, has a good SEO experience, works really nice to be honest.

I've built Rematch website with it and fitted for me perfectly. In a few weeks I'll could be a bit free to help on this task, if you're agree of course =)

**Comment by juanpicado** [comment]
hi @semoal , to be honest, yes. I thought about it. I'd love to have Gasbty.js but being honest if someone else doesn't do it, will never be done. 

Currently, we use v1 https://github.com/verdaccio/website and I fully ignore the advances on DC@v2 since I wrote the ticket, it seems

https://github.com/pnpm/pnpm.github.io/pull/91 `pnpm` is happy by far. I haven't read about https://docusaurus.io/docs/using-plugins by far maybe that helps a bit to improve what I was pursuing.

Somehow, if you want to move on, go ahead, if the website is fully migrated to V2, I'll desist of this ticket and close it, because I don't have the bandwidth in 2020 for it. 

I'll support you in all you need to make it done. Just ping me over the chat (discord) when you can work on it.

**Comment by juanpicado** [comment]
I'll remove the website folder on this repository, since this won't happen, with less code to maintain. The focus should be on migrate to Docusaurus v2.

**Comment by juanpicado** [comment]
@semoal just checking, do you have plans to work on this on the next 2 months? just asking, I'll be a bit free in August and maybe I give it a try on this repo.

**Comment by semoal** [comment]
> @semoal just checking, do you have plans to work on this on the next 2 months? just asking, I'll be a bit free in August and maybe I give it a try on this repo.

Yesss Juan, just finishing the Rematch book in approx 2 weeks. And I'll be available to give my best focus on this ;)

**Comment by juanpicado** [comment]
> > @semoal just checking, do you have plans to work on this on the next 2 months? just asking, I'll be a bit free in August and maybe I give it a try on this repo.
> 
> Yesss Juan, just finishing the Rematch book in approx 2 weeks. And I'll be available to give my best focus on this ;)

oh ok cool :) feel free to ping me if I can support you in something.

**Comment by juanpicado** [comment]
I just applied to https://www.netlify.com/legal/open-source-policy 🤞🏼

**Comment by ploh007** [comment]
@semoal I replied to you on twitter. 

But here is the link to the XD Design regenerated. Hopefully this works. I've removed the need for a password. 

[Verdaccio Website XD](https://xd.adobe.com/view/542108c7-2c48-4bed-b9da-bfe16fbf9ff6-0172/)

Given how dated the design is. It will require some updates. But looking at your work with the Rematch website, it'll be good. ;)

**Comment by juanpicado** [comment]
This sound great, btw yesterday I migrated all to Netlify. Now we can have build previews on pull requests.
