### ISSUE TITLE
Verdaccio 5 release

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#2141]
Since in April Node 10 is out of maintenance and Node 8 is already out since quite a while.

https://nodejs.org/en/about/releases/

I'll release Verdaccio 5 with only the **objective to get rid of problematic dependencies and forcing Node.js upgrade**, there will be only minor breaking changes on logger (bunyan over pino.js already done on `6.x`) and `npm token` experiment removing level #1925 (already implemented on 6.x). 

- Drop Node.js 8 and Node.js support #2142
- Upgrade Commander 7 #2143 
- [x] Pino.js over Bunyan (breaking change is no possibility to rotating file and or multi-stream support) related #1334  https://github.com/verdaccio/verdaccio/pull/1760 https://github.com/verdaccio/verdaccio/pull/2148
- [x] Get rid of LevelDB https://github.com/verdaccio/verdaccio/pull/2043 #1925  https://github.com/verdaccio/verdaccio/pull/2145 https://github.com/verdaccio/monorepo/pull/394
- [x] Revisit `url_prefix` behaviour #2122 

The development for `5.x` would become `6.x` and the biggest breaking changes will happen there in the future progressively.

https://github.com/verdaccio/verdaccio/discussions/1690

The version v4 would be move to maintenance mode for dependencies and security vulnerabilities, but the migration should be easy-peasy for the big majority.

**Comment by juanpicado** [comment]
```
npm i -g verdaccio@next
```
and 

```
docker pull verdaccio/verdaccio:5.x-next
```
