### ISSUE TITLE
WebUI Roadmap

### ISSUE THREAD

**Issue by Meeeeow** [verdaccio/verdaccio#221]
## Features need implement
- [x] Web UI #217 **(next minor release)**
- [x] Login **(next minor release)**
- [x] Use react-router **(should same as user center)**

## Refactoring
- [x] API clarify, move web ui only api to `/-/verdaccio/*` or some other path
- [x] Change directory structure, source code in `src` directory, shared code in `src/lib`, api & web api in `src/api/endpoint` & `src/api/web`
- [x] Move bundle.js and static directory out, they are not source code

## Discussion
- Try out react server-side render? **The first version will release a generated static file**
- Let web ui become a sub-project of verdaccio? **No**

## Future
The following features will be delivered in future versions
- Profile page (with plugin?), allow update password & manage token **(next next minor release)**
-  Better middleware, it's difficult to find out why `next({error: 'boom'})` works and who will handle it. docs & rewrite.
---

Fell free to share your idea or edit this roadmap.
@juanpicado

**Comment by juanpicado** [comment]
**Features**
* Web UI: 👍   `v2.3.0`
* Login 👍  `v2.3.0`
* Profile page: 👍  (but not plugin yet). We need to elaborate this part a bit more, endpoints? (I'd suggest on `v2.4.0`)
* Router: Depends of server-rendering I guess. `v2.3.0`

**Refactoring** `v2.3.0`
* web ui api 👍 
* middleware: Can you provide an example what's wrong and how it should be?
* directory structure: 👍  looks good. Using Babel, right?
* dist files 👍 

Additional topics:
* How unit/functional testing would looks like? and how to debug them if we use transpilers?
* We need to check all plugins, either babel, webpack or react are 100% compatible with Node 4 (yeah it sucks but, Node 4 still will be a headache for 10 months at least)
* We shouldn't forget #169 and #103 (refactoring topic)
* Build on Docker (#181 helps with this)
* (*I'll think on more topics soon*) 

**Discussion**
* Server rendering: There is a first try here (https://github.com/verdaccio/verdaccio/blob/refactoring-verdaccio/lib/web/server.js). I'm agreed that will be really nice, allowing use to play around with routers. So, I can see the benefit, not with the UI search, but on future features.
* Sub-project? I'm disagreed here. I do not want to track issues in multiples places, the UI will be used only here anyway, at least at the moment.

**Comment by juanpicado** [comment]
Fixed on #220
