### ISSUE TITLE
feature: Migrate the codebase to ES2015 (and up)

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#348]
**Type:** feature

**Description:**

This is a further step to modernizr the codebase. We are using Babel for the UI already and we want to take advance of it for the remaining code. The support old Node4,5 and 6 block us to use the latest features of Javascript. We have been done good progress along the 2017 with the new UI, migrate progressively to ES6 but we have to move on.

The following steps for migration would be:

- [x]  Add type checking (flow) #312
- [x]  Prepare build pipeline for Babel #349
- [x] Unit testing must support ES6 with the current set up, minor changes  #349
- [x] Create type definitions for flow (https://github.com/verdaccio/flow-types)
- [x] Update Docker build image for transpiling
- [x] Code coverage has to support ES6
- [x] Local storage must be extracted to separate repository using ES6 #291 

After these steps, the migration can continue progressively until is done.

**Comment by juanpicado** [comment]
I considered this issue solved on branch `3.x`
